// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubjectManagement.Data.EF;

namespace SubjectManagement.Data.Migrations
{
    [DbContext(typeof(SubjectDbContext))]
    partial class SubjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard.Data.Entities.AppUserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AppUserRole");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            RoleID = "admin",
                            UserID = "TK01"
                        },
                        new
                        {
                            ID = 2,
                            RoleID = "guest",
                            UserID = "TK02"
                        },
                        new
                        {
                            ID = 3,
                            RoleID = "guest",
                            UserID = "TK03"
                        },
                        new
                        {
                            ID = 4,
                            RoleID = "admin",
                            UserID = "TK04"
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.AlternativeSubject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("IDNew")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDOld")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("IDNew")
                        .IsUnique();

                    b.ToTable("AlternativeSubject");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.AppRole", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            ID = "admin",
                            Description = "Quyền Cao Cấp",
                            Name = "admin"
                        },
                        new
                        {
                            ID = "guest",
                            Description = "Quyền Người Xem",
                            Name = "guest"
                        },
                        new
                        {
                            ID = "dev",
                            Description = "Quyền Của Thằng Lập Trình",
                            Name = "dev"
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.AppUser", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            ID = "TK01",
                            Avatar = "",
                            FirstName = "Thuận",
                            LastName = "Võ Thành",
                            PasswordHash = "wZIa07fMB/OKgTNIFKmWVw==",
                            Username = "thuan"
                        },
                        new
                        {
                            ID = "TK02",
                            Avatar = "",
                            FirstName = "Anh",
                            LastName = "Lê Thị Ngọc",
                            PasswordHash = "X+vaPQ75BzemDeL9fG13KA==",
                            Username = "anh"
                        },
                        new
                        {
                            ID = "TK03",
                            Avatar = "",
                            FirstName = "Sơn",
                            LastName = "Nguyễn Ngọc",
                            PasswordHash = "SY08a/oDP23Bvk/MPDcKpw==",
                            Username = "son"
                        },
                        new
                        {
                            ID = "TK04",
                            Avatar = "",
                            FirstName = "Truyền",
                            LastName = "Nguyễn Thị Mỹ",
                            PasswordHash = "ipy+CjQc6p4LS8IWvcIq3Q==",
                            Username = "truyen"
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.Class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CodeClass = "DH19PM",
                            Name = "Kỹ thuật phầm mềm",
                            Year = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.ClassInFaculty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDClass")
                        .HasColumnType("int");

                    b.Property<int>("IDFaculty")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDClass")
                        .IsUnique();

                    b.HasIndex("IDFaculty");

                    b.ToTable("ClassInFaculty");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IDClass = 1,
                            IDFaculty = 1
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.ElectiveGroup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ElectiveGroup");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.Faculty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Faculty");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Công nghệ thông tin"
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.KnowledgeGroup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KnowledgeGroup");

                    b.HasData(
                        new
                        {
                            ID = new Guid("57955971-4be8-40fd-b149-eee225daea4c"),
                            Name = "Khối kiến thức đại cương"
                        },
                        new
                        {
                            ID = new Guid("d881a11f-bc9e-4f07-828f-9467c3045838"),
                            Name = "Khối kiến thức cơ sở ngành"
                        },
                        new
                        {
                            ID = new Guid("e3f2dfdf-85e9-40d1-adc1-95926f68011d"),
                            Name = "Khối kiến thức chuyên ngành"
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.Semester", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Semester");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Term = 1
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SemesterOfClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDClass")
                        .HasColumnType("int");

                    b.Property<int>("IDSemester")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDClass")
                        .IsUnique();

                    b.HasIndex("IDSemester");

                    b.ToTable("SemesterOfClass");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IDClass = 1,
                            IDSemester = 1
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.Subject", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOffical")
                        .HasColumnType("bit");

                    b.Property<int>("LearnFirst")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPractice")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTheory")
                        .HasColumnType("int");

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.Property<int>("Prerequisite")
                        .HasColumnType("int");

                    b.Property<bool>("TypeCourse")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            ID = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0010"),
                            CourseCode = "SEE101",
                            Credit = 1,
                            Details = "",
                            IsOffical = true,
                            LearnFirst = 0,
                            Name = "Giới thiệu ngành – ĐH KTPM",
                            NumberOfPractice = 0,
                            NumberOfTheory = 15,
                            Parallel = 0,
                            Prerequisite = 0,
                            TypeCourse = false
                        },
                        new
                        {
                            ID = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0011"),
                            CourseCode = "COS106",
                            Credit = 4,
                            Details = "",
                            IsOffical = true,
                            LearnFirst = 0,
                            Name = "Lập trình căn bản",
                            NumberOfPractice = 50,
                            NumberOfTheory = 35,
                            Parallel = 0,
                            Prerequisite = 0,
                            TypeCourse = false
                        },
                        new
                        {
                            ID = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0012"),
                            CourseCode = "TIE501",
                            Credit = 4,
                            Details = "",
                            IsOffical = true,
                            LearnFirst = 20,
                            Name = "Lập trình .Net",
                            NumberOfPractice = 60,
                            NumberOfTheory = 30,
                            Parallel = 0,
                            Prerequisite = 0,
                            TypeCourse = false
                        },
                        new
                        {
                            ID = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0013"),
                            CourseCode = "SEE301",
                            Credit = 2,
                            Details = "",
                            IsOffical = true,
                            LearnFirst = 0,
                            Name = "Nhập môn công nghệ phần mềm",
                            NumberOfPractice = 20,
                            NumberOfTheory = 20,
                            Parallel = 0,
                            Prerequisite = 0,
                            TypeCourse = true
                        },
                        new
                        {
                            ID = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0014"),
                            CourseCode = "SEE508",
                            Credit = 2,
                            Details = "",
                            IsOffical = true,
                            LearnFirst = 38,
                            Name = "Quản lý dự án phần mềm",
                            NumberOfPractice = 20,
                            NumberOfTheory = 20,
                            Parallel = 0,
                            Prerequisite = 0,
                            TypeCourse = true
                        },
                        new
                        {
                            ID = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0015"),
                            CourseCode = "SEE505",
                            Credit = 3,
                            Details = "",
                            IsOffical = true,
                            LearnFirst = 38,
                            Name = "Phân tích và thiết kế phần mềm hướng đối tượng",
                            NumberOfPractice = 30,
                            NumberOfTheory = 30,
                            Parallel = 0,
                            Prerequisite = 0,
                            TypeCourse = true
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SubjectInElectiveGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("IDElectiveGroup")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSubject")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("IDElectiveGroup");

                    b.HasIndex("IDSubject")
                        .IsUnique();

                    b.ToTable("SubjectInElectiveGroup");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SubjectInKnowledgeGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("IDKnowledgeGroup")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSubject")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("IDKnowledgeGroup");

                    b.HasIndex("IDSubject")
                        .IsUnique();

                    b.ToTable("SubjectInKnowledgeGroup");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IDKnowledgeGroup = new Guid("57955971-4be8-40fd-b149-eee225daea4c"),
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0010")
                        },
                        new
                        {
                            ID = 2,
                            IDKnowledgeGroup = new Guid("d881a11f-bc9e-4f07-828f-9467c3045838"),
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0011")
                        },
                        new
                        {
                            ID = 3,
                            IDKnowledgeGroup = new Guid("d881a11f-bc9e-4f07-828f-9467c3045838"),
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0012")
                        },
                        new
                        {
                            ID = 4,
                            IDKnowledgeGroup = new Guid("e3f2dfdf-85e9-40d1-adc1-95926f68011d"),
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0013")
                        },
                        new
                        {
                            ID = 5,
                            IDKnowledgeGroup = new Guid("e3f2dfdf-85e9-40d1-adc1-95926f68011d"),
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0014")
                        },
                        new
                        {
                            ID = 6,
                            IDKnowledgeGroup = new Guid("e3f2dfdf-85e9-40d1-adc1-95926f68011d"),
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0015")
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SubjectInSemester", b =>
                {
                    b.Property<Guid>("IDSubject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IDSemester")
                        .HasColumnType("int");

                    b.HasKey("IDSubject", "IDSemester");

                    b.HasIndex("IDSemester");

                    b.HasIndex("IDSubject")
                        .IsUnique();

                    b.ToTable("SubjectInSemester");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SubjectOfClass", b =>
                {
                    b.Property<int>("IDClass")
                        .HasColumnType("int");

                    b.Property<Guid>("IDSubject")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDClass", "IDSubject");

                    b.HasIndex("IDSubject")
                        .IsUnique();

                    b.ToTable("SubjectOfClass");

                    b.HasData(
                        new
                        {
                            IDClass = 1,
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0010")
                        },
                        new
                        {
                            IDClass = 1,
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0011")
                        },
                        new
                        {
                            IDClass = 1,
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0012")
                        },
                        new
                        {
                            IDClass = 1,
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0013")
                        },
                        new
                        {
                            IDClass = 1,
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0014")
                        },
                        new
                        {
                            IDClass = 1,
                            IDSubject = new Guid("0f7b55fc-4968-49d8-b9bd-402301fa0015")
                        });
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.AlternativeSubject", b =>
                {
                    b.HasOne("SubjectManagement.Data.Entities.Subject", "Subject")
                        .WithOne("AlternativeSubject")
                        .HasForeignKey("SubjectManagement.Data.Entities.AlternativeSubject", "IDNew")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.ClassInFaculty", b =>
                {
                    b.HasOne("SubjectManagement.Data.Entities.Class", "Class")
                        .WithOne("ClassInFaculty")
                        .HasForeignKey("SubjectManagement.Data.Entities.ClassInFaculty", "IDClass")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubjectManagement.Data.Entities.Faculty", "Faculty")
                        .WithMany("ClassInFaculties")
                        .HasForeignKey("IDFaculty")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SemesterOfClass", b =>
                {
                    b.HasOne("SubjectManagement.Data.Entities.Class", "Class")
                        .WithOne("SemesterOfClass")
                        .HasForeignKey("SubjectManagement.Data.Entities.SemesterOfClass", "IDClass")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubjectManagement.Data.Entities.Semester", "Semester")
                        .WithMany("SemesterOfClasses")
                        .HasForeignKey("IDSemester")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SubjectInElectiveGroup", b =>
                {
                    b.HasOne("SubjectManagement.Data.Entities.ElectiveGroup", "ElectiveGroup")
                        .WithMany("SubjectInElectiveGroups")
                        .HasForeignKey("IDElectiveGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubjectManagement.Data.Entities.Subject", "Subject")
                        .WithOne("SubjectInElectiveGroup")
                        .HasForeignKey("SubjectManagement.Data.Entities.SubjectInElectiveGroup", "IDSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectiveGroup");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SubjectInKnowledgeGroup", b =>
                {
                    b.HasOne("SubjectManagement.Data.Entities.KnowledgeGroup", "KnowledgeGroup")
                        .WithMany("SubjectInKnowledgeGroups")
                        .HasForeignKey("IDKnowledgeGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubjectManagement.Data.Entities.Subject", "Subject")
                        .WithOne("SubjectInKnowledgeGroup")
                        .HasForeignKey("SubjectManagement.Data.Entities.SubjectInKnowledgeGroup", "IDSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeGroup");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SubjectInSemester", b =>
                {
                    b.HasOne("SubjectManagement.Data.Entities.Semester", "Semester")
                        .WithMany("SubjectInSemesters")
                        .HasForeignKey("IDSemester")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubjectManagement.Data.Entities.Subject", "Subject")
                        .WithOne("SubjectInSemester")
                        .HasForeignKey("SubjectManagement.Data.Entities.SubjectInSemester", "IDSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.SubjectOfClass", b =>
                {
                    b.HasOne("SubjectManagement.Data.Entities.Class", "Class")
                        .WithMany("SubjectOfClass")
                        .HasForeignKey("IDClass")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubjectManagement.Data.Entities.Subject", "Subject")
                        .WithOne("SubjectOfClass")
                        .HasForeignKey("SubjectManagement.Data.Entities.SubjectOfClass", "IDSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.Class", b =>
                {
                    b.Navigation("ClassInFaculty");

                    b.Navigation("SemesterOfClass");

                    b.Navigation("SubjectOfClass");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.ElectiveGroup", b =>
                {
                    b.Navigation("SubjectInElectiveGroups");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.Faculty", b =>
                {
                    b.Navigation("ClassInFaculties");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.KnowledgeGroup", b =>
                {
                    b.Navigation("SubjectInKnowledgeGroups");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.Semester", b =>
                {
                    b.Navigation("SemesterOfClasses");

                    b.Navigation("SubjectInSemesters");
                });

            modelBuilder.Entity("SubjectManagement.Data.Entities.Subject", b =>
                {
                    b.Navigation("AlternativeSubject");

                    b.Navigation("SubjectInElectiveGroup");

                    b.Navigation("SubjectInKnowledgeGroup");

                    b.Navigation("SubjectInSemester");

                    b.Navigation("SubjectOfClass");
                });
#pragma warning restore 612, 618
        }
    }
}
